data:
  filepath: data/2024pr-qtr3rslt.pdf

  pdf:
    flavor: stream
    pages: "2"

  values_to_extract:
    Total revenues, net of interest expense: Total revenues, net of interest expense
    Citigroup's net income: Citigroup's net income (loss)
    Book value per share: Book value per share
    Tangible book value per share: Tangible book value per share
    Common Equity Tier 1 (CET1) Capital ratio: Common Equity Tier 1 (CET1) Capital ratio

models:
  name: mistralai/Mistral-7B-Instruct-v0.3